version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-backend
    ports:
      - '3003:3003'
    environment:
      - MONGO_URI_DEV=${MONGO_URI_DEV}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - mongo
    networks:
      - review-network

  mongo:
    image: mongo:6
    container_name: review-it-db
    ports:
      - '27017:27017'
    volumes:
      - /zoef/mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - review-network

volumes:
  mongo_data:

networks:
  review-network:
