name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: ${{ secrets.VPS_HOST }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: 'cd /zoef/review-it-backend && git pull origin main && docker-compose down && docker-compose up -d --build'
